package com.example.midterm_project

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a data model for a game score.
 *
 * <p>This entity is used to store individual game scores in a Room database. Each `Score` object
 * holds an ID (which is auto-generated), the player's name, and the number of attempts they took.</p>
 *
 * <p>The entity maps to a table named "scores" in the database. Each instance of this data class
 * translates to a row in the table with columns representing the class's properties.</p>
 *
 * Example Usage:
 * <pre>
 * val newScore = Score(playerName = "John", attempts = 5)
 * </pre>
 *
 * @property id The unique identifier for the score, auto-generated by the database.
 * @property playerName The name of the player associated with the score.
 * @property attempts The number of attempts taken by the player.
 *
 * @author Matt Gacek
 * @see androidx.room.Entity
 * @see androidx.room.PrimaryKey
 */
@Entity(tableName = "scores")
data class Score(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val playerName: String,
    val attempts: Int
)
